[package]
name = "s3-active-storage"
version = "0.1.0"
edition = "2021"
# Due to AWS SDK.
rust-version = "1.62.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
aws-credential-types = { version = "0.54", features = ["hardcoded-credentials"] }
aws-sdk-s3 = "0.24"
aws-smithy-http = "0.54"
aws-smithy-types = "0.54"
aws-types = "0.54"
axum = { version = "0.6", features = ["headers"] }
http = "*"
hyper = { version = "0.14", features = ["full"] }
maligned = "0.2.1"
mime = "0.3"
ndarray = "0.15"
ndarray-stats = "0.5"
num-traits = "0.2.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
strum_macros = "0.24"
thiserror = "1.0"
tokio = { version = "1.24", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.3", features = ["normalize-path", "trace", "validate-request"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }
zerocopy = { version = "0.6.1", features = ["alloc", "simd"] }
clap = { version = "4.2.1", features = ["derive", "env"] }

[dev-dependencies]
regex = "1"
serde_test = "1.0"
