[package]
name = "s3-active-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
tokio = { version = "1.24", features = ["full"] }
tower = "0.4"
url = { version = "2", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
serde_test = "1.0"
