[package]
name = "s3-active-storage"
version = "0.1.0"
edition = "2021"
# Due to AWS SDK.
rust-version = "1.62.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
aws-config = "0.54"
aws-credential-types = { version = "0.54", features = ["hardcoded-credentials"] }
aws-sdk-s3 = "0.24"
aws-types = "0.54"
axum = { version = "0.6", features = ["headers"] }
hyper = { version = "0.14", features = ["full"] }
maligned = "0.2.1"
mime = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
thiserror = "1.0"
tokio = { version = "1.24", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.3", features = ["normalize-path", "trace", "validate-request"] }
url = { version = "2", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
regex = "1"
serde_test = "1.0"
