#!/usr/bin/env bash

# Use timestamped storage volume so that test data is removed when container is stopped
exec docker run --detach --rm -p 9000:9000 -p 9001:9001 -v minio_$(date +%s) --name minio minio/minio server data --console-address ":9001"
