#!/usr/bin/env bash

set -e

origin=$(dirname "$0")
origin=$(cd "$origin"; pwd)
me=$(basename "$0")

volume="$1"
if [ -z "$volume" ]; then
    cat <<EOF

usage: $me <path to share>

EOF
    exit 1
fi
volume=$(cd "$volume"; pwd)

# Start our local nginx
# https://hub.docker.com/_/nginx
echo "Starting nginx serving on '$volume'"
docker run \
    --name nginx-user-share \
    --rm \
    -d \
    -p 8000:80 \
    -v "$origin/nginx.conf:/etc/nginx/conf.d/default.conf" \
    -v "$origin/htpasswd:/etc/nginx/htpasswd" \
    -v "$volume:/usr/share/nginx/html" \
    docker.io/nginx

